book_review_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from posts import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')), 
    path('users/', include('django.contrib.auth.urls')), 
    path('pages/', include('pages.urls')), 
    path('',views.home, name='home'),
    path('posts/', include('posts.urls')), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView,  Post
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('post/upload', Post, name='upload'),
]

posts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import (
PostsUpdateView,
PostsDeleteView,)
urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('myposts/', views.my_posts, name='my_posts'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('<int:pk>/edit/',PostsUpdateView.as_view(), name='post_edit'), 
    path('<int:pk>/delete/', PostsDeleteView.as_view(), name='post_delete'),
    path('follow/<int:user_id>/', views.follow_unfollow_user, name='follow_unfollow_user'), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import SignUpView
from . import views
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', views.custom_logout_view, name='logout'),
]

pages/models.py
from django.db import models

# Create your models here.
class Page(models.Model):
    content = models.TextField()
class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='media/images/', null=True, blank=True)

    def __str__(self):
        return self.title

posts/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=255, blank=True, null=True)
    genre = models.CharField(max_length=255, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_posts', blank=True)
    created_by = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE, null=True, blank=True)
  
    class Meta:
        ordering = ['-created_at']

    def total_likes(self):
        return self.likes.count()
    
    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.conf import settings
# Create your models here.
from django.contrib.auth.models import AbstractUser
class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)
    following = models.ManyToManyField('self', symmetrical=False, related_name='followers', blank=True)

    def __str__(self):
        return self.username

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'author', 'genre']  
        labels = {
            'title': 'Book Title:',
            'content': 'Review:',
            'image': 'Image:'
        }
class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields =  ('username', 'email', 'age',) 
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields =  ('username', 'email', 'age',) 

pages/views.py
from django.shortcuts import render
from .models import Post 
# Create your views here.
from django.views.generic import TemplateView
class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['posts'] = Post.objects.all()  
        return context

posts/views.py
from django.shortcuts import render, redirect
from .forms import PostForm
from .models import Post
from django.contrib.auth.models import User
from .forms import SearchForm
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.http import JsonResponse  
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from users.models import CustomUser

def upload(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.created_by = request.user  
            post.save()
            return redirect('home')
        
    else: 
        form = PostForm()

    return render(request, 'upload.html', {'form': form})

def home(request):
    search_query = request.GET.get('search', '')  
    sort_by = request.GET.get('sort', '')
    posts = Post.objects.all() 
    if search_query:
        posts = posts.filter(title__icontains=search_query)  
    if sort_by == 'most_liked':
        posts = posts.annotate(like_count=Count('likes')).order_by('-like_count', '-created_at')
    else:
        posts = posts.order_by('-created_at')
    context = {
        'posts': posts,
        'search_query': search_query,
        'sort_by': sort_by,
    }
    return render(request, 'home.html', context)

User = get_user_model()

@login_required
def like_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user
    liked = False
    if post.likes.filter(id=user.id).exists():
        post.likes.remove(user) 
    else:
        post.likes.add(user)  
        liked = True
    data = {
        'liked': liked,
        'total_likes': post.total_likes(),
    }
    return JsonResponse(data)

@login_required
def my_posts(request):
    user_posts = Post.objects.filter(created_by=request.user)
    context = {
        'posts': user_posts,
        'followers_count': request.user.followers.count(),  
        'following_count': request.user.following.count(),  
    }
    return render(request, 'my_posts.html', context)  
# Create your views here.
class PostsUpdateView(UpdateView): 
    model = Post
    fields = ('title', 'author','genre','content','image')
    template_name = 'post_edit.html'
    success_url = reverse_lazy('my_posts')

class PostsDeleteView(DeleteView): 
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('my_posts')

@login_required
def follow_unfollow_user(request, user_id):
    target_user = get_object_or_404(CustomUser, id=user_id)
    user = request.user

    if user == target_user:
        return JsonResponse({'error': 'You cannot follow yourself'}, status=400)

    if target_user in user.following.all():
        user.following.remove(target_user)
        followed = False
    else:
        user.following.add(target_user)
        followed = True

    data = {
        'followed': followed,
        'followers_count': target_user.followers.count(),
    }
    return JsonResponse(data)

def profile(request, user_id):
    profile_user = get_object_or_404(CustomUser, id=user_id)
    context = {
        'profile_user': profile_user,
        'followers_count': profile_user.followers.count(), 
    }
    return render(request, 'home.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CustomUserCreationForm
from django.contrib.auth import logout
from django.contrib import messages
from django.shortcuts import redirect

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'
def custom_logout_view(request):
    logout(request)
    messages.success(request, "You are logged out.")
    return redirect('home')  

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
        <style>
            body {
                background-color: #ffffff; 
                color: #1c8585; 
                font-family: 'Arial', sans-serif;
            }
            .navbar {
                background-color: #b0a498; 
                padding: 1rem 2rem;
                box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
            }
            .navbar-brand {
                font-weight: bold;
                font-size: 1.5rem;
                color: #ffffff !important;
            }
            .nav-link, .dropdown-toggle {
                color: #ffffff !important; 
                margin-right: 1rem;
                font-size: 1.1rem;
            }
            .nav-link:hover, .dropdown-item:hover {
                color: #b3e0cc !important; 
            }
            .navbar-toggler {
                border-color: #ffffff;
            }
            .navbar-toggler-icon {
                background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3E%3Cpath stroke='rgba(255, 255, 255, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
            }
            .btn-primary {
                background-color: #1c8585;
                border-color: #1c8585;
                border-radius: 30px;
                padding: 0.5rem 1.5rem;
            }
            .btn-primary:hover {
                background-color: #276d48;
                border-color: #276d48;
            }
            .btn-outline-secondary {
                border-color: #1c8585;
                color: #1c8585;
                border-radius: 30px;
                padding: 0.5rem 1.5rem;
            }
            .btn-outline-secondary:hover {
                background-color: #1c8585;
                color: #ffffff;
            }
            .dropdown-menu {
                background-color: #1c8585; 
                border-radius: 0;
            }
            .dropdown-item {
                color: #ffffff;
            }
            .dropdown-item:hover {
                background-color: #276d48; 
                color: #ffffff;
            }
            .dropdown-divider {
                border-color: #ffffff;
            }
            .container {
                padding-top: 2rem;
                padding-bottom: 2rem;
            }
            .card {
                border: none;
                box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
                margin-bottom: 2rem;
            }
            .card-header {
                background-color: #a08264;
                color: #ffffff;
                font-weight: bold;
                font-size: 1.2rem;
                text-align: center;
            }
            .card-body {
                padding: 2rem;
                font-size: 1rem;
                color: #000000;
            }
            .footer {
                background-color: #b0a498;
                color: #ffffff;
                padding: 1rem 0;
                text-align: center;
                margin-top: 4rem;
            }
        </style>
        <title>{% block title %}Book Review{% endblock title %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4">
            <a class="navbar-brand" href="{% url 'home' %}">Books Review</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                    {% if user.is_authenticated %}
                        <ul class="navbar-nav ml-auto">
                            <li>
                                <a class="nav-link" href="{% url 'my_posts' %}">My Posts</a> 
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'upload' %}">+ Post</a> 
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {{ user.username }}
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                    <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                                </div>
                            </li>
                        </ul>
                    {% else %}
                        <form class="form-inline ml-auto">
                            <a href="{% url 'login' %}" class="btn btn-outline-secondary">
                            Log In</a>
                            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">
                            Sign up</a>
                        </form>
                    {% endif %}
            </div>
        </nav>
            <div class="container">
                <div class="card">
                    <div class="card-header">
                        {% if user.is_authenticated %}
                            <form method="GET" action="{% url 'home' %}">
                                <input type="text" name="search" placeholder="Search Books..." value="{{ search_query }}">
                                <button type="submit">Search</button>
                                <label for="sort">Sort By:</label>
                                <select name="sort" id="sort" onchange="this.form.submit()">
                                    <option value="" {% if not sort_by %}selected{% endif %}>--</option>
                                    <option value="most_liked" {% if sort_by == 'most_liked' %}selected{% endif %}>Most Liked</option>
                                </select>
                            </form>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        {% block content %}
                        {% endblock content %}
                    </div>
                </div>
            </div>
        <footer class="footer">
        </footer>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
    Hi {{ user.username }}!
{% endif %}

<h4>Latest Posts</h4>
<ul>
    {% for post in posts %}
        <li style="display: flex; align-items: center; margin-bottom: 20px;">
            <img style='width: 200px; border-radius: 15px;' src="{{ post.image.url }}" alt="{{ post.title }}" width="300px" style="margin-right: 20px;">
            <div style="padding: 3%;">
                {{ post.created_by.username }} 
                {% if user.is_authenticated and user != post.created_by %}
                    <button id="follow-button-{{ post.created_by.id }}" class="follow-button" data-user-id="{{ post.created_by.id }}">
                        {% if user in post.created_by.followers.all %}
                            Unfollow
                        {% else %}
                            Follow
                        {% endif %}
                    </button>
                    <p id="follow-count-{{ post.created_by.id }}">{{ post.created_by.followers.count }} Followers</p>
                {% endif %}
                <h3>{{ post.title }}</h3>
                <p>By {{ post.author }}</p>
                <p>Genre: {{ post.genre }}</p>
                <p>{{ post.content }}</p>
                <button type="button" id="like-button-{{ post.id }}" class="like-button">
                    {% if user in post.likes.all %}
                        Unlike
                    {% else %}
                        Like
                    {% endif %}
                </button>
                <p id="like-count-{{ post.id }}">{{ post.total_likes }} likes</p>

                <a href="https://kdgnpc98-8000.uks1.devtunnels.ms/">Download Book</a>
            </div>
        </li>
    {% empty %}
        <p>No posts found.</p>
    {% endfor %}
</ul>

<script>
    document.querySelectorAll('.like-button').forEach(function(button) {
        button.addEventListener('click', function() {
            const postId = this.id.split('-')[2];
            const xhr = new XMLHttpRequest();
            xhr.open('POST', `/posts/like/${postId}/`);  
            xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
            xhr.onload = function() {
                if (xhr.status === 200) {
                    const response = JSON.parse(xhr.responseText);
                    const likeButton = document.getElementById(`like-button-${postId}`);
                    const likeCount = document.getElementById(`like-count-${postId}`);
                    likeButton.innerText = response.liked ? 'Unlike' : 'Like';
                    likeCount.innerText = `${response.total_likes} likes`;
                }
            };
            xhr.send();
        });
    });

    document.querySelectorAll('.follow-button').forEach(function(button) {
        button.addEventListener('click', function() {
            const userId = this.dataset.userId; 
            const xhr = new XMLHttpRequest();
            xhr.open('POST', `posts/follow/${userId}/`);  
            xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}'); 

            xhr.onload = function() {
                if (xhr.status === 200) {
                    const response = JSON.parse(xhr.responseText); 
                    const followButton = document.getElementById(`follow-button-${userId}`); 
                    const followCount = document.getElementById(`follow-count-${userId}`); 
                    followButton.innerText = response.followed ? 'Unfollow' : 'Follow';
                    followCount.innerText = `${response.followers_count} Followers`;
                }
            };

            xhr.send(); 
        });
    });
</script>

{% endblock content %}

templates/my_posts.html
{% extends 'base.html' %}
{% block title %}My Posts{% endblock title %}
{% block content %}
    <h4>My Posts</h4>
    <p>Followers: {{ followers_count }}</p>
    <p>Following: {{ following_count }}</p>
    <ul>
        {% for post in posts %}
            <li style="display: flex; align-items: center; margin-bottom: 20px;">
                <img style='width: 200px; border-radius: 15px;' src="{{ post.image.url }}" alt="{{ post.title }}" width="300px" style="margin-right: 20px;">
                <div style="padding: 3%;">
                    <h3>{{ post.title }}</h3>
                    <p>Genre: {{ post.genre }}</p>
                    <p>{{ post.content }}</p>
                    <p>{{ post.total_likes }} likes</p>
                </div>
            </li>
            <div>
                <p><a href="{% url 'post_edit' post.pk %}">Edit</a> |
                    <a href="{% url 'post_delete' post.pk %}">Delete</a></p>
            </div>
        {% empty %}
            <p>You haven't posted anything yet.</p>
        {% endfor %}
    </ul>
{% endblock content %}

templates/post_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}
{% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sign Up{% endblock title %}
{% block content %}
<h2>Sign Up</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button  class="btn btn-success" type="submit">Sign Up</button>
</form>
{% endblock content %}

templates/upload.html
{% extends 'base.html' %}
{% block title %}Upload{% endblock title %}
{% block content %}
<h2>Create Post</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="id_title">Book Title:</label>
    {{ form.title }}
    <br>
    <label for="id_title">Author:</label>
    {{ form.author }}
    <br>
    <label for="id_title">Genre:</label>
    {{ form.genre }}
    <br>
    <label for="id_content">Write Review:</label>
    {{ form.content }}
    <br>
    <label for="id_image">Book Cover:</label>
    {{ form.image }}
    <br>
    <button type="submit">Post</button>
</form>
{% endblock content %}